---
- name: Prepare molecule instance
  hosts: all[0]
  gather_facts: no
  tasks:
  - name: Create a network with custom IPAM config
    delegate_to: localhost
    community.general.docker_network:
      name: keepalived-network
      state: absent
