- name: Prepare Ubuntu hosts
  hosts: ubuntu
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Update APT package cache
      ansible.builtin.package:
        name:
          - iproute2
        state: present
