---
- name: Converge
  hosts: all
  # sorted is necessary to reliably know which one will be the first master node
  order: sorted
  serial:
    - "1"
    - "100%"
  tasks:
  - name: Apt update and install rsync, ping, iproute
    ansible.builtin.package:
      update_cache: yes
      name:
        - rsync
        - inetutils-ping
        - iproute2
      state: present
    when: ansible_os_family == "Debian"

  - name: Yum install iproute to fix undefined ansible_default_ipv4.address
    ansible.builtin.package:
      name: iproute
      state: present
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "7"

  - name: Add a container to a network, leaving existing containers connected
    delegate_to: localhost
    community.docker.docker_network:
      name: keepalived-network
      connected:
        - "{{ inventory_hostname }}"
      appends: yes

  - name: Re-collect network facts required after installation iproute
    ansible.builtin.setup:
      gather_subset: network

  - name: Show ansible_interfaces
    ansible.builtin.debug:
      var: ansible_interfaces

  - name: Define vrrp nic
    ansible.builtin.set_fact:
      vrrp_nic: "{{ ((ansible_interfaces | reject('equalto','lo')) | difference([ansible_default_ipv4.interface]))[0] | string }}"

  - name: Include keepalived vars
    ansible.builtin.include_vars:
      file: ../../tests/keepalived_haproxy_combined_example.yml

  - name: Include ansible-keepalived
    ansible.builtin.include_role:
      name: ansible-keepalived

  - name: half way done
    ansible.builtin.debug:
      msg: "--- --- --- --- UPDATE CONFIGURATION --- --- --- ---"

  - name: Include keepalived edit vars
    ansible.builtin.include_vars: "../../tests/keepalived_haproxy_combined_edit_example.yml"

  - name: Include ansible-keepalived
    ansible.builtin.include_role:
      name: ansible-keepalived
