---
- name: Ensure all vrrp nics are up
  shell: ip link set dev {{ vrrp_nic }} up || ifconfig {{ vrrp_nic }} up
  changed_when: false
- name: Testing failover on {{ master_hostname }}
  debug:
    var: master_hostname
    verbosity: 3
- name: Bringing the interfaces down
  shell: ip link set {{ vrrp_nic }} down || ifconfig {{ vrrp_nic }} down
  changed_when: false
  when: inventory_hostname != master_hostname
- name: The VRRP state needs to adapt the topo change
  wait_for:
    timeout: 8
- setup:
    gather_subset: network
- debug:
    var: ansible_all_ipv4_addresses
- assert:
    that:
      - "'192.168.33.2' in ansible_all_ipv4_addresses"
  when: inventory_hostname == master_hostname
