---
lint: |
  set -e
  yamllint .
  ansible-lint -vv --exclude=.tox
dependency:
  name: galaxy
driver:
  name: docker
verifier:
  name: ansible
provisioner:
  name: ansible
  options:
    v: True
  log: True
platforms:
  - name: keepalived-centos7
    ## Do not use pre_build_image, instead build it from the Dockerfile.j2
    #pre_build_image: yes
    #image: centos:7
    ## The Dockerfile.j2 will build image from https://github.com/ericsysmin/docker-ansible-images/
    # Jeff geerling now has images, I trust those more than ericsysmin can use them.
    pre_build_image: yes
    image: geerlingguy/docker-centos7-ansible
    privileged: true
    command: /sbin/init
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: keepalived-centos8
    pre_build_image: yes
    image: geerlingguy/docker-centos8-ansible:latest
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: keepalived-rockylinux8
    pre_build_image: yes
    image: geerlingguy/docker-rockylinux8-ansible:latest
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: keepalived-xenial
    pre_build_image: yes
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    service_manager: systemd

  - name: keepalived-bionic
    pre_build_image: yes
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: keepalived-focal
    pre_build_image: yes
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
