---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  # This is necessary to ensure the _first_ node is indeed master
  order: sorted
  gather_facts: yes
  tasks:
    - name: Define vrrp nic
      ansible.builtin.set_fact:
        vrrp_nic: "{{ ((ansible_interfaces | reject('equalto','lo')) | difference([ansible_default_ipv4.interface]))[0] | string }}"

    - name: Show ansible facts
      ansible.builtin.debug:
        var: ansible_facts
        verbosity: 3

    - name: Get present instance configurations
      ansible.builtin.command: "ls -la {{ keepalived_config_directory_path }}/instances/"
      changed_when: false
      register: dir_out

    - name: Ensure the first node is master
      ansible.builtin.assert:
        that:
          - "'ipv4_secondaries' in ansible_{{ vrrp_nic }}"
          - "ansible_{{ vrrp_nic }}['ipv4_secondaries'][0]['address'] == '192.168.33.2'"
          - dir_out.stdout_lines == 'int.conf'
      when: inventory_hostname == ansible_play_hosts[0]
