---
name: Monthly Test
on:
  schedule:
    # Run on the 10th of each month at noon.
    - cron: '00 12 10 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox: ["lint"]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt remove ansible
          sudo apt install tox
      - name: Lint test with tox
        run: |
          sudo -H -E tox -e lint
