---
name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # not running molecule_basic in CI due to lack of support
        # of macos image with nested virt + vagrant
        tox: ["lint"]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install tox
      - name: Test using tox
        run: |
          sudo -H -E tox -e ${{ matrix.tox }}
